/* 247WC — textos en español (rioplatense) e inglés.
   El idioma sale del teléfono (es* → español, el resto → inglés) y se puede
   forzar desde el modal de info. Las claves son cortas; los valores con
   variables son funciones. */

const DICT = {
  es: {
    title: '247WC — Baños públicos cerca tuyo',
    mapAria: 'Mapa de baños públicos cercanos',
    statusAriaIdle: 'Sin ubicación. Tocá para escanear baños.',
    statusTap: (v) => `${v.text}. Tocá para ${v.list ? 'ver la lista' : 'escanear'}.`,
    infoAria: 'Información y ajustes',
    settingsAria: 'Ajustes',
    settings: 'Ajustes',
    close: 'Cerrar',
    appearance: 'Apariencia',
    theme: 'Tema', themeAuto: 'Auto', themeLight: 'Claro', themeDark: 'Oscuro',
    about: 'Acerca de',
    dataSources: 'Datos',
    install: 'Instalar',
    installHow: 'Compartir → Agregar a inicio',
    advanced: 'Avanzado',
    openMaps: 'Abrir en Google Maps',
    open24h: 'Abierto 24 h',
    days: { Mo: 'Lu', Tu: 'Ma', We: 'Mi', Th: 'Ju', Fr: 'Vi', Sa: 'Sa', Su: 'Do' },
    gender: { unisex: 'Unisex', both: 'Hombres y mujeres', male: 'Solo hombres', female: 'Solo mujeres' },
    yes: 'Sí',
    aFee: 'Costo', aHours: 'Horario', aAccess: 'Acceso', aGender: 'Género', aWheel: 'Accesibilidad', aChanging: 'Cambiador', aFlush: 'Descarga', aFloor: 'Piso', aNote: 'Nota',
    locateAria: 'Centrar en mi ubicación',
    scanFab: 'Escanear baños',
    scanning: 'Escaneando…',
    fabZone: 'Buscar en esta zona',
    fabZoneBusy: 'Buscando en esta zona…',
    fabResume: 'Seguir guiando',
    fabRetry: 'Reintentar',
    fabBusiness: 'Sumar bares y negocios',
    fabHome: 'Volver a mi ubicación',
    sheetAria: 'Baños cercanos',
    listTitle: 'Baños cerca',
    business: 'Incluir bares y negocios',
    filtersAria: 'Filtros',
    fFree: 'Gratis', fOpen24: '24 h', fWheelchair: 'Accesible', fChanging: 'Cambiador',
    creditsData: 'Datos de',
    creditsAnd: 'y',
    missing: '¿Falta un baño?',
    nearest: 'El más cercano',
    guide: 'Guiarme',
    seeAll: 'Ver todos',
    seeN: (v) => `Ver los ${v.n}`,
    seeInList: 'Ver en la lista',
    backList: 'Lista',
    guideWalk: 'Guiarme caminando',
    share: 'Compartir',
    steps: 'Ver indicaciones',
    disclaimer: 'Datos de la comunidad: puede que algún baño esté cerrado. Si ves un error, corregilo en OpenStreetMap.',
    wBuscar: 'Buscar', wEncontrar: 'Encontrar', wLlegar: 'Llegar',
    onb1Title: 'Escaneá 3 km a la redonda',
    onb1Sub: 'Un toque y buscamos los baños públicos que tenés cerca. Gratis y sin cuenta.',
    onb2Title: 'El más cercano, primero',
    onb2Sub: 'Te mostramos cuál te queda más cerca y si es gratis, accesible o abre 24 h. Si hay pocos, sumás bares y negocios.',
    onb3Title: 'Una brújula te lleva',
    onb3Sub: 'Te guiamos caminando hasta la puerta. Para eso usamos tu ubicación, solo para buscar: no guardamos nada.',
    onbNext: 'Siguiente',
    onbSkip: 'Saltar',
    onbLater: 'Ahora no',
    onbAllow: 'Activar ubicación',
    onbStep: (v) => `Paso ${v.n} de 3`,
    onbAgain: 'Ver la introducción',
    artNear: 'Baños a 3\u00a0km',
    artFree: 'Gratis o pago',
    art24: 'Abierto 24\u00a0h',
    artGuide: 'Guía con brújula',
    scanTitle: 'El baño más cercano',
    scanSub: 'Tocá escanear y buscamos los baños públicos que tenés alrededor.',
    scanLocating: 'Ubicándote…',
    scanLocatingSub: 'Dale permiso a la ubicación si el navegador te lo pregunta.',
    scanSearching: 'Escaneando la zona…',
    scanSearchingSub: 'Buscando baños en OpenStreetMap alrededor tuyo.',
    scanAgain: 'Escanear de nuevo',
    retry: 'Reintentar',
    scanBusiness: 'Buscar también en bares y negocios',
    scanManual: 'Buscar sin ubicación',
    scanDismiss: 'Ver el mapa sin escanear',
    emptyTitle: 'No hay baños mapeados acá',
    emptySubBiz: 'Ni baños públicos ni negocios con baño a menos de 3 km.',
    emptySub: 'No hay baños públicos cargados a menos de 3 km. Probá activando bares y negocios.',
    emptyHelp: '¿Conocés uno? Sumalo desde «¿Falta un baño?» al final de la lista y queda disponible para todo el mundo.',
    dataTitle: 'No pudimos buscar',
    dataSub: 'Las bases de baños no están respondiendo en este momento.',
    dataHelp: '<strong>No es que no haya baños cerca: no pudimos averiguarlo.</strong><br>Los datos salen de OpenStreetMap y de Refuge Restrooms, que a veces se saturan. Probá de nuevo en unos segundos.',
    dataStatus: 'Las fuentes de datos no responden',
    locTitle: 'No pudimos ubicarte',
    locSub: 'Sin ubicación no podemos ordenar los baños por cercanía.',
    locStatus: 'Sin ubicación · tocá para reintentar',
    noGeo: 'Este navegador no comparte la ubicación. Probá con Chrome o Safari.',
    noHttps: 'La página tiene que abrirse en https:// para poder usar la ubicación.',
    gpsTimeout: 'El GPS tardó demasiado. Probá cerca de una ventana o al aire libre, con la ubicación del teléfono encendida, y tocá Reintentar.',
    gpsUnavailable: 'El teléfono no pudo darnos la posición. Fijate que la ubicación esté activada en el sistema y tocá Reintentar.',
    deniedHead: '<strong>El navegador no nos deja acceder a la ubicación.</strong><br>',
    deniedIos: [
      '<strong>1.</strong> Si no estás en Safari (Chrome, Comet, Arc, o el navegador dentro de otra app): andá a <strong>Ajustes → Privacidad y seguridad → Localización</strong>, buscá ese navegador y poné <em>Al usar la app</em>. Casi todos vienen con el GPS apagado.',
      '<strong>2.</strong> Si estás en Safari: tocá <strong>aA</strong> en la barra de direcciones → <strong>Ajustes del sitio web</strong> → Ubicación → <em>Preguntar</em> o <em>Permitir</em>.',
      '<strong>3.</strong> Si no aparece ninguna de las dos, <button type="button" class="linkish" id="scan-copy">copiá el link</button> y abrilo en Safari.',
    ],
    deniedOther: [
      '<strong>1.</strong> Tocá el candado de la barra de direcciones → Permisos → Ubicación → Permitir.',
      '<strong>2.</strong> Revisá que el navegador tenga permiso de ubicación en los ajustes del sistema.',
      '<strong>3.</strong> Si abriste el link dentro de otra app (Instagram, WhatsApp), abrilo en el navegador.',
    ],
    guideCloseAria: 'Salir de la guía',
    sheetToggle: 'Expandir o contraer la lista',
    goingTo: 'Yendo a',
    distance: 'Distancia',
    walking: 'caminando',
    walkingLabel: 'Caminando',
    compassOn: 'Activar brújula',
    guideHint: 'Seguí la flecha. Vibra cuando estés llegando.',
    calcRoute: 'Calculando la mejor ruta…',
    arrived: '¡Llegaste! El baño está acá mismo.',
    followArrow: 'Seguí la flecha',
    walkTowards: (v) => `Caminá hacia ${v.dir}`,
    noCompassHint: 'Sin brújula, la flecha apunta según el norte del mapa.',
    seeMap: 'Ver en el mapa',
    cardW: 'O',
    untilStep: (v) => `Seguí hasta ${v.dist}: ${v.text}`,
    cardinals: ['el norte', 'el noreste', 'el este', 'el sureste', 'el sur', 'el suroeste', 'el oeste', 'el noroeste'],
    noCompass: 'Sin brújula la flecha apunta según el norte del mapa',
    compassFail: 'No se pudo activar la brújula',
    infoP: 'El baño público más cercano, sin vueltas. <strong>Tu ubicación no se guarda</strong>: se usa en el teléfono para ordenar por cercanía, y a nuestra búsqueda solo llega el punto a consultar, que no se almacena.',
    infoFree: '<strong>Gratis y sin cuenta.</strong>',
    infoInstall: '<strong>Instalable.</strong> Compartir → «Agregar a inicio».',
    infoData: '<strong>Datos de la comunidad.</strong> OpenStreetMap y Refuge Restrooms.',
    language: 'Idioma',
    diag: 'Diagnóstico',
    reset: 'Reiniciar la app (borra la caché)',
    done: 'Listo',
    km: 'km', min: 'min', h: 'h',
    publicToilet: 'Baño público',
    publicToiletBy: (v) => `Baño público · ${v.op}`,
    shopWithToilet: 'Local con baño',
    biz: { cafe: 'Café', restaurant: 'Restaurante', fast_food: 'Comida rápida', bar: 'Bar', pub: 'Bar', fuel: 'Estación de servicio', library: 'Biblioteca', mall: 'Shopping', supermarket: 'Supermercado', community_centre: 'Centro comunitario', hospital: 'Hospital', bus_station: 'Terminal', townhall: 'Municipalidad', marketplace: 'Mercado', station: 'Estación', park: 'Parque' },
    bPaid: 'Pago', bFree: 'Gratis', bWheelchair: 'Accesible', bChanging: 'Cambiador', bUnisex: 'Unisex', bCustomers: 'Solo clientes', bPrivate: 'Privado', bInside: 'Dentro de un local', bFlush: 'Con agua',
    noData: 'Sin más datos',
    noDataLoaded: 'Sin más datos cargados',
    hours: 'Horario:', floor: 'Piso:', lastCheck: 'Última revisión:',
    straightLine: '(en línea recta)',
    emptyFiltered: 'Ningún baño cumple con esos filtros. Probá sacando alguno.',
    emptyNone: 'No encontramos baños mapeados cerca. Probá activando «Bares y negocios» o mové el mapa y tocá «Buscar en esta zona».',
    nToilets: (v) => `${v.n} ${v.n === 1 ? 'baño' : 'baños'}`,
    nearYou: (v) => `${v.n} cerca tuyo`,
    inZone: (v) => `${v.n} en esta zona`,
    noneFilters: 'Ningún baño pasa los filtros',
    noneZone: 'No hay baños mapeados en esta zona',
    statusIdle: 'Sin ubicación todavía',
    statusScanning: 'Escaneando baños cerca tuyo',
    statusSearching: 'Buscando baños cerca…',
    statusOffline: 'Sin conexión: mostrando lo último guardado',
    statusFail: 'No pudimos buscar. Tocá para reintentar',
    posDenied: 'Activá el permiso de ubicación para ver baños cerca',
    posUnavailable: 'No pudimos ubicarte. Probá al aire libre o con el GPS activo',
    posTimeout: 'La ubicación está tardando demasiado',
    posOther: 'No pudimos acceder a tu ubicación',
    toastSources: 'Las fuentes de datos no responden. Probá de nuevo en unos segundos.',
    toastNoneNear: 'No hay baños cargados a menos de 3 km. Probá con bares y negocios.',
    toastCopied: 'Link copiado. Pegalo en Safari y dale permiso a la ubicación.',
    toastCopyManual: (v) => `${v.host} — copiá esta dirección y abrila en Safari`,
    toastManual: 'Mové el mapa a la zona que quieras y tocá «Buscar en esta zona»',
    toastLink: 'Link copiado',
    toastContribute: 'Sumá el baño en OpenStreetMap y lo ve todo el mundo',
    shareText: (v) => `${v.name} — baño a ${v.dist}`,
    mapFail: 'No se pudo cargar el mapa. Revisá la conexión y recargá.',
    osrm: { left: 'a la izquierda', right: 'a la derecha', straight: 'derecho', 'slight left': 'leve a la izquierda', 'slight right': 'leve a la derecha', 'sharp left': 'bien a la izquierda', 'sharp right': 'bien a la derecha', uturn: 'en U' },
    osrmDepart: (v) => `Arrancá${v.street}`,
    osrmArrive: 'Llegaste al baño',
    osrmTurn: (v) => (v.dir === 'derecho' ? `Seguí derecho${v.street}` : `Doblá ${v.dir}${v.street}`),
    osrmVia: (v) => ` por ${v.name}`,
    zoomIn: 'Acercar', zoomOut: 'Alejar', zoomGroup: 'Zoom del mapa',
    handoffTitle: 'Escaneá con la cámara del teléfono',
    handoffSub: 'Se abre la ruta a pie en Google Maps, sin instalar nada.',
    handoffCopy: 'Copiar link',
    handoffQrAria: 'Código QR con la ruta a pie en Google Maps',
    handoffNoQr: 'No pudimos generar el QR. Copiá el link o abrí la ruta en Google Maps.',
    toastLinkFail: 'No pudimos copiar el link. Abrí la ruta con el botón de Google Maps.',
    approxLoc: 'Ubicación aproximada: las distancias pueden variar unos cientos de metros.',
    welcomeTitle: 'Encontrá el baño más cercano',
    welcomeSub: 'Escaneá y te mostramos los baños públicos a 3 km, ordenados por cercanía.',
    valhallaLang: 'es-ES',

    // Con mouse (compu): no hay brújula ni GPS, se hace clic y la guía sigue en el teléfono.
    mouse: {
      statusAriaIdle: 'Sin ubicación. Hacé clic para escanear baños.',
      statusTap: (v) => `${v.text}. Hacé clic para ${v.list ? 'ver la lista' : 'escanear'}.`,
      scanSub: 'Hacé clic en escanear y buscamos los baños públicos que tenés alrededor.',
      locStatus: 'Sin ubicación · hacé clic para reintentar',
      statusFail: 'No pudimos buscar. Hacé clic para reintentar',
      installHow: 'Chrome o Edge: ícono de instalar en la barra de direcciones',
      guide: 'Seguir en el teléfono',
      guideWalk: 'Seguir en el teléfono',
      onb3Title: 'Te llevamos hasta la puerta',
      onb3Sub: 'Ves la ruta a pie en el mapa y con un QR la seguís en el teléfono. Usamos tu ubicación solo para buscar: no guardamos nada.',
      artGuide: 'Ruta a pie',
      toastManual: 'Mové el mapa a la zona que quieras y hacé clic en «Buscar en esta zona»',
      posUnavailable: 'No pudimos ubicarte. Revisá que el Wi‑Fi y la ubicación del sistema estén activos',
      posTimeout: 'La ubicación está tardando: en una compu sale del Wi‑Fi',
      gpsTimeout: 'La ubicación tardó demasiado. En una compu sale del Wi‑Fi: revisá que esté prendido y hacé clic en Reintentar.',
      gpsUnavailable: 'La compu no pudo darnos la posición. Revisá que la ubicación esté activada en los ajustes del sistema y que el Wi‑Fi esté prendido, y hacé clic en Reintentar.',
      deniedOther: [
        '<strong>1.</strong> Hacé clic en el candado (o en el ícono de ajustes) a la izquierda de la dirección → Ubicación → Permitir, y recargá la página.',
        '<strong>2.</strong> Revisá que el sistema deje usar la ubicación: en Mac, Ajustes del Sistema → Privacidad y seguridad → Localización; en Windows, Configuración → Privacidad → Ubicación.',
        '<strong>3.</strong> Si sigue sin andar, abrí la app en el teléfono: ahí el GPS es mucho más preciso.',
      ],
    },
  },

  en: {
    title: '247WC — Public toilets near you',
    mapAria: 'Map of nearby public toilets',
    statusAriaIdle: 'No location yet. Tap to scan for toilets.',
    statusTap: (v) => `${v.text}. Tap to ${v.list ? 'see the list' : 'scan'}.`,
    infoAria: 'Info and settings',
    settingsAria: 'Settings',
    settings: 'Settings',
    close: 'Close',
    appearance: 'Appearance',
    theme: 'Theme', themeAuto: 'Auto', themeLight: 'Light', themeDark: 'Dark',
    about: 'About',
    dataSources: 'Data',
    install: 'Install',
    installHow: 'Share → Add to Home Screen',
    advanced: 'Advanced',
    openMaps: 'Open in Google Maps',
    open24h: 'Open 24 h',
    days: { Mo: 'Mon', Tu: 'Tue', We: 'Wed', Th: 'Thu', Fr: 'Fri', Sa: 'Sat', Su: 'Sun' },
    gender: { unisex: 'Unisex', both: 'Men and women', male: 'Men only', female: 'Women only' },
    yes: 'Yes',
    aFee: 'Cost', aHours: 'Hours', aAccess: 'Access', aGender: 'Gender', aWheel: 'Accessibility', aChanging: 'Changing table', aFlush: 'Flush', aFloor: 'Floor', aNote: 'Note',
    locateAria: 'Center on my location',
    scanFab: 'Scan for toilets',
    scanning: 'Scanning…',
    fabZone: 'Search this area',
    fabZoneBusy: 'Searching this area…',
    fabResume: 'Resume guide',
    fabRetry: 'Try again',
    fabBusiness: 'Add bars and shops',
    fabHome: 'Back to my location',
    sheetAria: 'Nearby toilets',
    listTitle: 'Toilets nearby',
    business: 'Include bars and shops',
    filtersAria: 'Filters',
    fFree: 'Free', fOpen24: '24 h', fWheelchair: 'Accessible', fChanging: 'Changing table',
    creditsData: 'Data from',
    creditsAnd: 'and',
    missing: 'Missing a toilet?',
    nearest: 'Closest one',
    guide: 'Guide me',
    seeAll: 'See all',
    seeN: (v) => `See all ${v.n}`,
    seeInList: 'See in list',
    backList: 'List',
    guideWalk: 'Guide me on foot',
    share: 'Share',
    steps: 'Show directions',
    disclaimer: 'Community data: a toilet may be closed. If you spot a mistake, fix it on OpenStreetMap.',
    wBuscar: 'Search', wEncontrar: 'Find', wLlegar: 'Arrive',
    onb1Title: 'Scan 3 km around you',
    onb1Sub: 'One tap and we find the public toilets near you. Free, no account.',
    onb2Title: 'Closest first',
    onb2Sub: 'We show you the nearest one and whether it is free, accessible or open 24 h. If there are few, add bars and shops.',
    onb3Title: 'A compass takes you there',
    onb3Sub: 'We guide you on foot to the door. For that we use your location, only to search: we store nothing.',
    onbNext: 'Next',
    onbSkip: 'Skip',
    onbLater: 'Not now',
    onbAllow: 'Turn on location',
    onbStep: (v) => `Step ${v.n} of 3`,
    onbAgain: 'Show the intro',
    artNear: 'Toilets within 3\u00a0km',
    artFree: 'Free or paid',
    art24: 'Open 24\u00a0h',
    artGuide: 'Compass guide',
    scanTitle: 'The closest toilet',
    scanSub: 'Tap scan and we find the public toilets around you.',
    scanLocating: 'Locating you…',
    scanLocatingSub: 'Allow location if your browser asks.',
    scanSearching: 'Scanning the area…',
    scanSearchingSub: 'Looking for toilets on OpenStreetMap around you.',
    scanAgain: 'Scan again',
    retry: 'Try again',
    scanBusiness: 'Also search bars and shops',
    scanManual: 'Search without location',
    scanDismiss: 'See the map without scanning',
    emptyTitle: 'No toilets mapped here',
    emptySubBiz: 'No public toilets and no shops with a toilet within 3 km.',
    emptySub: 'No public toilets mapped within 3 km. Try including bars and shops.',
    emptyHelp: 'Know one? Add it via “Missing a toilet?” at the bottom of the list and everyone gets it.',
    dataTitle: "Couldn't search",
    dataSub: 'The toilet databases are not responding right now.',
    dataHelp: "<strong>It's not that there are no toilets nearby: we couldn't find out.</strong><br>Data comes from OpenStreetMap and Refuge Restrooms, which sometimes get overloaded. Try again in a few seconds.",
    dataStatus: 'Data sources not responding',
    locTitle: "Couldn't locate you",
    locSub: 'Without your location we can’t sort toilets by distance.',
    locStatus: 'No location · tap to retry',
    noGeo: "This browser doesn't share location. Try Chrome or Safari.",
    noHttps: 'The page must be opened over https:// to use location.',
    gpsTimeout: 'GPS took too long. Try near a window or outdoors, with location turned on, and tap Try again.',
    gpsUnavailable: "Your phone couldn't provide a position. Check that location is enabled in system settings and tap Try again.",
    deniedHead: '<strong>The browser is not letting us access your location.</strong><br>',
    deniedIos: [
      "<strong>1.</strong> If you're not in Safari (Chrome, Comet, Arc, or a browser inside another app): go to <strong>Settings → Privacy & Security → Location Services</strong>, find that browser and set <em>While Using the App</em>. Most come with GPS off.",
      "<strong>2.</strong> If you're in Safari: tap <strong>aA</strong> in the address bar → <strong>Website Settings</strong> → Location → <em>Ask</em> or <em>Allow</em>.",
      '<strong>3.</strong> If neither shows up, <button type="button" class="linkish" id="scan-copy">copy the link</button> and open it in Safari.',
    ],
    deniedOther: [
      '<strong>1.</strong> Tap the lock in the address bar → Permissions → Location → Allow.',
      '<strong>2.</strong> Check the browser has location permission in system settings.',
      '<strong>3.</strong> If you opened the link inside another app (Instagram, WhatsApp), open it in the browser.',
    ],
    guideCloseAria: 'Exit guidance',
    sheetToggle: 'Expand or collapse the list',
    goingTo: 'Going to',
    distance: 'Distance',
    walking: 'walking',
    walkingLabel: 'Walking',
    compassOn: 'Enable compass',
    guideHint: "Follow the arrow. It vibrates when you're arriving.",
    calcRoute: 'Finding the best route…',
    arrived: "You're here! The toilet is right here.",
    followArrow: 'Follow the arrow',
    walkTowards: (v) => `Walk ${v.dir}`,
    noCompassHint: 'Without a compass, the arrow points relative to map north.',
    seeMap: 'See on the map',
    cardW: 'W',
    untilStep: (v) => `Continue for ${v.dist}: ${v.text}`,
    cardinals: ['north', 'northeast', 'east', 'southeast', 'south', 'southwest', 'west', 'northwest'],
    noCompass: 'Without a compass the arrow points relative to map north',
    compassFail: "Couldn't enable the compass",
    infoP: 'The closest public toilet, no fuss. <strong>Your location is not stored</strong>: it is used on your phone to sort by distance, and our search only receives the point to look up, which is not kept.',
    infoFree: '<strong>Free, no account.</strong>',
    infoInstall: '<strong>Installable.</strong> Share → “Add to Home Screen”.',
    infoData: '<strong>Community data.</strong> OpenStreetMap and Refuge Restrooms.',
    language: 'Language',
    diag: 'Diagnostics',
    reset: 'Reset the app (clears cache)',
    done: 'Done',
    km: 'km', min: 'min', h: 'h',
    publicToilet: 'Public toilet',
    publicToiletBy: (v) => `Public toilet · ${v.op}`,
    shopWithToilet: 'Shop with toilet',
    biz: { cafe: 'Café', restaurant: 'Restaurant', fast_food: 'Fast food', bar: 'Bar', pub: 'Pub', fuel: 'Petrol station', library: 'Library', mall: 'Mall', supermarket: 'Supermarket', community_centre: 'Community centre', hospital: 'Hospital', bus_station: 'Bus station', townhall: 'Town hall', marketplace: 'Market', station: 'Station', park: 'Park' },
    bPaid: 'Paid', bFree: 'Free', bWheelchair: 'Accessible', bChanging: 'Changing table', bUnisex: 'Unisex', bCustomers: 'Customers only', bPrivate: 'Private', bInside: 'Inside a shop', bFlush: 'Flush',
    noData: 'No more details',
    noDataLoaded: 'No more details available',
    hours: 'Hours:', floor: 'Floor:', lastCheck: 'Last checked:',
    straightLine: '(straight line)',
    emptyFiltered: 'No toilet matches those filters. Try removing one.',
    emptyNone: 'No mapped toilets nearby. Try “Bars and shops” or move the map and tap “Search this area”.',
    nToilets: (v) => `${v.n} ${v.n === 1 ? 'toilet' : 'toilets'}`,
    nearYou: (v) => `${v.n} near you`,
    inZone: (v) => `${v.n} in this area`,
    noneFilters: 'No toilet passes the filters',
    noneZone: 'No toilets mapped in this area',
    statusIdle: 'No location yet',
    statusScanning: 'Scanning toilets near you',
    statusSearching: 'Searching nearby toilets…',
    statusOffline: 'Offline: showing last saved results',
    statusFail: "Couldn't search. Tap to retry",
    posDenied: 'Allow location to see toilets nearby',
    posUnavailable: "Couldn't locate you. Try outdoors or with GPS on",
    posTimeout: 'Location is taking too long',
    posOther: "Couldn't access your location",
    toastSources: 'Data sources not responding. Try again in a few seconds.',
    toastNoneNear: 'No toilets within 3 km. Try bars and shops.',
    toastCopied: 'Link copied. Paste it in Safari and allow location.',
    toastCopyManual: (v) => `${v.host} — copy this address and open it in Safari`,
    toastManual: 'Move the map to any area and tap “Search this area”',
    toastLink: 'Link copied',
    toastContribute: 'Add the toilet on OpenStreetMap and everyone sees it',
    shareText: (v) => `${v.name} — toilet ${v.dist} away`,
    mapFail: "Couldn't load the map. Check your connection and reload.",
    osrm: { left: 'left', right: 'right', straight: 'straight', 'slight left': 'slightly left', 'slight right': 'slightly right', 'sharp left': 'sharp left', 'sharp right': 'sharp right', uturn: 'a U-turn' },
    osrmDepart: (v) => `Start${v.street}`,
    osrmArrive: 'You have arrived',
    osrmTurn: (v) => (v.dir === 'straight' ? `Continue straight${v.street}` : `Turn ${v.dir}${v.street}`),
    osrmVia: (v) => ` on ${v.name}`,
    zoomIn: 'Zoom in', zoomOut: 'Zoom out', zoomGroup: 'Map zoom',
    handoffTitle: 'Scan with your phone camera',
    handoffSub: 'The walking route opens in Google Maps, nothing to install.',
    handoffCopy: 'Copy link',
    handoffQrAria: 'QR code with the walking route in Google Maps',
    handoffNoQr: "Couldn't create the QR code. Copy the link or open the route in Google Maps.",
    toastLinkFail: "Couldn't copy the link. Open the route with the Google Maps button.",
    approxLoc: 'Approximate location: distances may be off by a few hundred metres.',
    welcomeTitle: 'Find the closest toilet',
    welcomeSub: 'Scan and we show the public toilets within 3 km, sorted by distance.',
    valhallaLang: 'en-US',

    mouse: {
      statusAriaIdle: 'No location yet. Click to scan for toilets.',
      statusTap: (v) => `${v.text}. Click to ${v.list ? 'see the list' : 'scan'}.`,
      scanSub: 'Click scan and we find the public toilets around you.',
      locStatus: 'No location · click to retry',
      statusFail: "Couldn't search. Click to retry",
      installHow: 'Chrome or Edge: install icon in the address bar',
      guide: 'Continue on your phone',
      guideWalk: 'Continue on your phone',
      onb3Title: 'We take you to the door',
      onb3Sub: 'See the walking route on the map and continue on your phone with a QR code. We only use your location to search: we store nothing.',
      artGuide: 'Walking route',
      toastManual: 'Move the map to any area and click “Search this area”',
      posUnavailable: "Couldn't locate you. Check that Wi‑Fi and system location are on",
      posTimeout: 'Location is taking a while: computers get it from Wi‑Fi',
      gpsTimeout: 'Location took too long. Computers get it from Wi‑Fi: make sure it is on and click Try again.',
      gpsUnavailable: "Your computer couldn't provide a position. Check that location is enabled in system settings and Wi‑Fi is on, then click Try again.",
      deniedOther: [
        '<strong>1.</strong> Click the lock (or settings icon) left of the address → Location → Allow, then reload the page.',
        '<strong>2.</strong> Check the system allows location: on Mac, System Settings → Privacy & Security → Location Services; on Windows, Settings → Privacy → Location.',
        '<strong>3.</strong> If it still fails, open the app on your phone: its GPS is far more precise.',
      ],
    },
  },
};

function detect() {
  try {
    const saved = localStorage.getItem('247wc:lang');
    if (saved === 'es' || saved === 'en') return saved;
  } catch { /* modo privado */ }
  return /^es/i.test(navigator.language || '') ? 'es' : 'en';
}

export const LANG = detect();

// Mouse o trackpad (compu): se lee una sola vez para que los textos y lo que
// hace la app nunca se contradigan, aunque un convertible cambie de modo.
export const MOUSE = typeof matchMedia === 'function' && matchMedia('(hover: hover) and (pointer: fine)').matches;

export function t(key, vars) {
  const dict = DICT[LANG] || DICT.es;
  const v = (MOUSE ? dict.mouse?.[key] : undefined) ?? dict[key] ?? DICT.es[key] ?? key;
  return typeof v === 'function' ? v(vars || {}) : v;
}

export function setLang(lang) {
  try { localStorage.setItem('247wc:lang', lang); } catch { /* nada */ }
}

// Aplica las claves marcadas en el HTML: data-i18n (texto), data-i18n-html
// (con etiquetas), data-i18n-aria (aria-label) y data-i18n-title (tooltip).
export function applyI18n() {
  document.documentElement.lang = LANG;
  document.documentElement.dataset.input = MOUSE ? 'mouse' : 'touch';
  document.title = t('title');
  document.querySelectorAll('[data-i18n]').forEach((n) => { n.textContent = t(n.dataset.i18n); });
  document.querySelectorAll('[data-i18n-html]').forEach((n) => { n.innerHTML = t(n.dataset.i18nHtml); });
  document.querySelectorAll('[data-i18n-aria]').forEach((n) => { n.setAttribute('aria-label', t(n.dataset.i18nAria)); });
  document.querySelectorAll('[data-i18n-title]').forEach((n) => { n.title = t(n.dataset.i18nTitle); });
}
